:haproxy:
  :instances:
    'ha1': 'http://ks3277700.kimsufi.com:8888/haproxy'

  :username: ''
  :password: ''
  :pxname_exclude:
  :pxname_include:
  :svname_exclude:
    - 'backend'
    - 'frontend'
  :svname_include:
  :critical: 90.0
  :warning: 80.0
